/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Component creado para el modelo iPhone 13 Pro
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function IPhone13ProModel({ screenTexture, ...props }) {
  const group = useRef()
  const { scene, nodes, materials } = useGLTF('/iphone13pro.glb')
  
  // Aplicar la textura de pantalla al material correspondiente
  useEffect(() => {
    if (screenTexture && scene) {
      scene.traverse((node) => {
        if (node.isMesh) {
          const material = node.material
          
          // Buscar el mesh de la pantalla por nombre o propiedades
          const nodeName = node.name.toLowerCase()
          const materialName = material.name?.toLowerCase() || ''
          
          // Detectar si es la pantalla del iPhone
          if (nodeName.includes('screen') || 
              nodeName.includes('display') || 
              nodeName.includes('lcd') ||
              materialName.includes('screen') || 
              materialName.includes('display') ||
              materialName.includes('lcd')) {
            
            // Clonar el material para no afectar otros objetos
            node.material = material.clone()
            node.material.map = screenTexture
            node.material.emissive = new THREE.Color(0xffffff)
            node.material.emissiveMap = screenTexture
            node.material.emissiveIntensity = 1
            node.material.toneMapped = true
            node.material.needsUpdate = true
          }
        }
      })
    }
  }, [screenTexture, scene])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  )
}

// Preload del modelo para mejor rendimiento
useGLTF.preload('/iphone13pro.glb')

